/*
 * @author Mário Soares
 * @contributors Jefferson González
 * @contributors René Vögeli / Rangee GmbH
 * 
 * @license 
 * This file is part of wxPHP check the LICENSE file for information.
 * 
 * @note
 * This file was auto-generated by the wxPHP source maker
*/

#ifndef WXPHP_AUI_H_GUARD
#define WXPHP_AUI_H_GUARD

#include "references.h"
#include "object_types.h"
#include "arginfo_void.h"

ZEND_BEGIN_ARG_INFO_EX(wxphp_aui_get_args, 0, 0, 1)
    ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

extern zend_class_entry* php_wxAuiToolBarEvent_entry;
extern zend_object_handlers wxphp_wxAuiToolBarEvent_object_handlers;
void php_wxAuiToolBarEvent_destruction_handler(zend_resource*);

class wxAuiToolBarEvent_php: public wxAuiToolBarEvent{
    public:

    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxAuiToolBarEvent{
    wxAuiToolBarEvent_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxAuiToolBarEvent;

void php_wxAuiToolBarEvent_free(void *object);
zend_object* php_wxAuiToolBarEvent_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxAuiToolBarEvent_functions[] = {
    PHP_ME(php_wxAuiToolBarEvent, GetClickPoint, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarEvent, GetItemRect, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarEvent, GetToolId, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarEvent, IsDropDownClicked, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxAuiToolBarEvent * php_wxAuiToolBarEvent_fetch_object(zend_object *obj) {
    return (zo_wxAuiToolBarEvent *)(
        (char *)(obj) - XtOffsetOf(zo_wxAuiToolBarEvent, zo)
    );
}

#define Z_wxAuiToolBarEvent_P(zv) \
    php_wxAuiToolBarEvent_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxAuiToolBarItem_entry;
extern zend_object_handlers wxphp_wxAuiToolBarItem_object_handlers;
void php_wxAuiToolBarItem_destruction_handler(zend_resource*);

class wxAuiToolBarItem_php: public wxAuiToolBarItem{
    public:

    wxAuiToolBarItem_php(const wxAuiToolBarItem& c):wxAuiToolBarItem(c){}
    wxAuiToolBarItem_php():wxAuiToolBarItem(){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxAuiToolBarItem{
    wxAuiToolBarItem_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxAuiToolBarItem;

void php_wxAuiToolBarItem_free(void *object);
zend_object* php_wxAuiToolBarItem_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxAuiToolBarItem_functions[] = {
    PHP_ME(php_wxAuiToolBarItem, __construct, arginfo_void, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxAuiToolBarItem, SetWindow, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetUserData, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetSticky, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetState, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetSpacerPixels, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetSizerItem, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetShortHelp, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetProportion, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetMinSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetLongHelp, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetLabel, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetKind, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetId, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetHoverBitmap, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetHasDropDown, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetDisabledBitmap, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetBitmap, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetAlignment, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, SetActive, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, IsSticky, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, IsActive, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, HasDropDown, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetWindow, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetUserData, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetState, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetSpacerPixels, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetSizerItem, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetShortHelp, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetProportion, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetMinSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetLongHelp, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetLabel, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetKind, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetId, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetHoverBitmap, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetDisabledBitmap, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetBitmap, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, GetAlignment, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBarItem, Assign, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxAuiToolBarItem * php_wxAuiToolBarItem_fetch_object(zend_object *obj) {
    return (zo_wxAuiToolBarItem *)(
        (char *)(obj) - XtOffsetOf(zo_wxAuiToolBarItem, zo)
    );
}

#define Z_wxAuiToolBarItem_P(zv) \
    php_wxAuiToolBarItem_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxAuiToolBarArt_entry;
extern zend_object_handlers wxphp_wxAuiToolBarArt_object_handlers;
void php_wxAuiToolBarArt_destruction_handler(zend_resource*);

class wxAuiToolBarArt_php: public wxAuiToolBarArt{
    public:

    
    wxAuiToolBarArt* Clone();
    void DrawBackground(wxDC& dc, wxWindow* wnd, const wxRect& rect);
    void DrawButton(wxDC& dc, wxWindow* wnd, const wxAuiToolBarItem& item, const wxRect& rect);
    void DrawControlLabel(wxDC& dc, wxWindow* wnd, const wxAuiToolBarItem& item, const wxRect& rect);
    void DrawDropDownButton(wxDC& dc, wxWindow* wnd, const wxAuiToolBarItem& item, const wxRect& rect);
    void DrawGripper(wxDC& dc, wxWindow* wnd, const wxRect& rect);
    void DrawLabel(wxDC& dc, wxWindow* wnd, const wxAuiToolBarItem& item, const wxRect& rect);
    void DrawOverflowButton(wxDC& dc, wxWindow* wnd, const wxRect& rect, int state);
    void DrawSeparator(wxDC& dc, wxWindow* wnd, const wxRect& rect);
    int GetElementSize(int element_id);
    unsigned int GetFlags();
    wxFont GetFont();
    wxSize GetLabelSize(wxDC& dc, wxWindow* wnd, const wxAuiToolBarItem& item);
    int GetTextOrientation();
    wxSize GetToolSize(wxDC& dc, wxWindow* wnd, const wxAuiToolBarItem& item);
    void SetElementSize(int element_id, int size);
    void SetFlags(unsigned int flags);
    void SetFont(const wxFont& font);
    void SetTextOrientation(int orientation);
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxAuiToolBarArt{
    wxAuiToolBarArt_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxAuiToolBarArt;

void php_wxAuiToolBarArt_free(void *object);
zend_object* php_wxAuiToolBarArt_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxAuiToolBarArt_functions[] = {
    PHP_FE_END
};
#endif


static inline zo_wxAuiToolBarArt * php_wxAuiToolBarArt_fetch_object(zend_object *obj) {
    return (zo_wxAuiToolBarArt *)(
        (char *)(obj) - XtOffsetOf(zo_wxAuiToolBarArt, zo)
    );
}

#define Z_wxAuiToolBarArt_P(zv) \
    php_wxAuiToolBarArt_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxAuiDefaultToolBarArt_entry;
extern zend_object_handlers wxphp_wxAuiDefaultToolBarArt_object_handlers;
void php_wxAuiDefaultToolBarArt_destruction_handler(zend_resource*);

class wxAuiDefaultToolBarArt_php: public wxAuiDefaultToolBarArt{
    public:

    wxAuiDefaultToolBarArt_php():wxAuiDefaultToolBarArt(){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxAuiDefaultToolBarArt{
    wxAuiDefaultToolBarArt_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxAuiDefaultToolBarArt;

void php_wxAuiDefaultToolBarArt_free(void *object);
zend_object* php_wxAuiDefaultToolBarArt_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxAuiDefaultToolBarArt_functions[] = {
    PHP_ME(php_wxAuiDefaultToolBarArt, CloneMethod, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, DrawBackground, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, DrawButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, DrawControlLabel, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, DrawDropDownButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, DrawGripper, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, DrawLabel, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, DrawOverflowButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, DrawSeparator, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, GetElementSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, GetFlags, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, GetFont, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, GetLabelSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, GetTextOrientation, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, GetToolSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, SetElementSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, SetFlags, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, SetFont, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, SetTextOrientation, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiDefaultToolBarArt, __construct, arginfo_void, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxAuiDefaultToolBarArt * php_wxAuiDefaultToolBarArt_fetch_object(zend_object *obj) {
    return (zo_wxAuiDefaultToolBarArt *)(
        (char *)(obj) - XtOffsetOf(zo_wxAuiDefaultToolBarArt, zo)
    );
}

#define Z_wxAuiDefaultToolBarArt_P(zv) \
    php_wxAuiDefaultToolBarArt_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxAuiToolBar_entry;
extern zend_object_handlers wxphp_wxAuiToolBar_object_handlers;
void php_wxAuiToolBar_destruction_handler(zend_resource*);

class wxAuiToolBar_php: public wxAuiToolBar{
    public:

    wxAuiToolBar_php():wxAuiToolBar(){}
    wxAuiToolBar_php(wxWindow* parent, wxWindowID id=wxID_ANY, const wxPoint& position=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxAUI_TB_DEFAULT_STYLE):wxAuiToolBar(parent, id, position, size, style){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxAuiToolBar{
    wxAuiToolBar_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxAuiToolBar;

void php_wxAuiToolBar_free(void *object);
zend_object* php_wxAuiToolBar_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxAuiToolBar_functions[] = {
    PHP_ME(php_wxAuiToolBar, __construct, arginfo_void, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxAuiToolBar, AddControl, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, AddLabel, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, AddSeparator, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, AddSpacer, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, AddStretchSpacer, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, Clear, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, ClearTools, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, DeleteByIndex, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, DeleteTool, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, EnableTool, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, ToggleTool, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetWindowStyleFlag, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolTextOrientation, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolSticky, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolShortHelp, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolSeparation, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolProportion, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolPacking, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolLongHelp, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolLabel, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolDropDown, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolBorderPadding, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolBitmapSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetToolBitmap, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetOverflowVisible, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetMargins, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetGripperVisible, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, SetFont, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, Realize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, IsPaneValid, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetWindowStyleFlag, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolToggled, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolTextOrientation, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolSticky, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolShortHelp, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolSeparation, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, FindControl, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, FindTool, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, FindToolByIndex, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, FindToolByPosition, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetArtProvider, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetGripperVisible, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetHintSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetOverflowVisible, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolBarFits, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolBitmap, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolBitmapSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolBorderPadding, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolCount, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolDropDown, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolEnabled, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolFits, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolFitsByIndex, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolIndex, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolLabel, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolLongHelp, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolPacking, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolPos, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolProportion, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, GetToolRect, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiToolBar, AddTool, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxAuiToolBar * php_wxAuiToolBar_fetch_object(zend_object *obj) {
    return (zo_wxAuiToolBar *)(
        (char *)(obj) - XtOffsetOf(zo_wxAuiToolBar, zo)
    );
}

#define Z_wxAuiToolBar_P(zv) \
    php_wxAuiToolBar_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxAuiNotebook_entry;
extern zend_object_handlers wxphp_wxAuiNotebook_object_handlers;
void php_wxAuiNotebook_destruction_handler(zend_resource*);

class wxAuiNotebook_php: public wxAuiNotebook{
    public:

    wxAuiNotebook_php(wxWindow* parent, wxWindowID id=wxID_ANY, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxAUI_NB_DEFAULT_STYLE):wxAuiNotebook(parent, id, pos, size, style){}
    wxAuiNotebook_php():wxAuiNotebook(){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxAuiNotebook{
    wxAuiNotebook_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxAuiNotebook;

void php_wxAuiNotebook_free(void *object);
zend_object* php_wxAuiNotebook_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxAuiNotebook_functions[] = {
    PHP_ME(php_wxAuiNotebook, __construct, arginfo_void, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxAuiNotebook, Split, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, ShowWindowMenu, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, SetUniformBitmapSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, SetTabCtrlHeight, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, SetSelectedFont, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, SetPageText, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, SetPageImage, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, SetPageBitmap, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, SetNormalFont, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, SetMeasuringFont, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, SetFont, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, SetArtProvider, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, RemovePage, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, GetTabCtrlHeight, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, GetSelection, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, GetPageText, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, GetPageIndex, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, GetPageCount, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, GetPageBitmap, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, GetPage, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, GetHeightForPageHeight, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, GetCurrentPage, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, GetArtProvider, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, DeletePage, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, DeleteAllPages, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, Create, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, ChangeSelection, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, AdvanceSelection, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, AddPage, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiNotebook, SetSelection, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxAuiNotebook * php_wxAuiNotebook_fetch_object(zend_object *obj) {
    return (zo_wxAuiNotebook *)(
        (char *)(obj) - XtOffsetOf(zo_wxAuiNotebook, zo)
    );
}

#define Z_wxAuiNotebook_P(zv) \
    php_wxAuiNotebook_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxAuiTabArt_entry;
extern zend_object_handlers wxphp_wxAuiTabArt_object_handlers;
void php_wxAuiTabArt_destruction_handler(zend_resource*);

class wxAuiTabArt_php: public wxAuiTabArt{
    public:

    
    void SetSizingInfo(const wxSize& tab_ctrl_size, size_t tab_count);
    void SetSelectedFont(const wxFont& font);
    void SetNormalFont(const wxFont& font);
    void SetMeasuringFont(const wxFont& font);
    void SetFlags(unsigned int flags);
    void SetColour(const wxColour& colour);
    void SetActiveColour(const wxColour& colour);
    wxSize GetTabSize(wxDC& dc, wxWindow* wnd, const wxString& caption, const wxBitmap& bitmap, bool active, int close_button_state, int* x_extent);
    int GetIndentSize();
    void DrawButton(wxDC& dc, wxWindow* wnd, const wxRect& in_rect, int bitmap_id, int button_state, int orientation, wxRect* out_rect);
    void DrawBackground(wxDC& dc, wxWindow* wnd, const wxRect& rect);
    wxAuiTabArt* Clone();
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxAuiTabArt{
    wxAuiTabArt_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxAuiTabArt;

void php_wxAuiTabArt_free(void *object);
zend_object* php_wxAuiTabArt_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxAuiTabArt_functions[] = {
    PHP_FE_END
};
#endif


static inline zo_wxAuiTabArt * php_wxAuiTabArt_fetch_object(zend_object *obj) {
    return (zo_wxAuiTabArt *)(
        (char *)(obj) - XtOffsetOf(zo_wxAuiTabArt, zo)
    );
}

#define Z_wxAuiTabArt_P(zv) \
    php_wxAuiTabArt_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxAuiDockArt_entry;
extern zend_object_handlers wxphp_wxAuiDockArt_object_handlers;
void php_wxAuiDockArt_destruction_handler(zend_resource*);

class wxAuiDockArt_php: public wxAuiDockArt{
    public:

    wxAuiDockArt_php():wxAuiDockArt(){}
    
    void SetMetric(int id, int new_val);
    void SetFont(int id, const wxFont& font);
    int GetMetric(int id);
    void SetColour(int id, const wxColour& colour);
    wxFont GetFont(int id);
    wxColour GetColour(int id);
    void DrawSash(wxDC& dc, wxWindow* window, int orientation, const wxRect& rect);
    void DrawPaneButton(wxDC& dc, wxWindow* window, int button, int button_state, const wxRect& rect, wxAuiPaneInfo& pane);
    void DrawGripper(wxDC& dc, wxWindow* window, const wxRect& rect, wxAuiPaneInfo& pane);
    void DrawCaption(wxDC& dc, wxWindow* window, const wxString& text, const wxRect& rect, wxAuiPaneInfo& pane);
    void DrawBorder(wxDC& dc, wxWindow* window, const wxRect& rect, wxAuiPaneInfo& pane);
    void DrawBackground(wxDC& dc, wxWindow* window, int orientation, const wxRect& rect);
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxAuiDockArt{
    wxAuiDockArt_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxAuiDockArt;

void php_wxAuiDockArt_free(void *object);
zend_object* php_wxAuiDockArt_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxAuiDockArt_functions[] = {
    PHP_ME(php_wxAuiDockArt, __construct, arginfo_void, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxAuiDockArt * php_wxAuiDockArt_fetch_object(zend_object *obj) {
    return (zo_wxAuiDockArt *)(
        (char *)(obj) - XtOffsetOf(zo_wxAuiDockArt, zo)
    );
}

#define Z_wxAuiDockArt_P(zv) \
    php_wxAuiDockArt_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxAuiManager_entry;
extern zend_object_handlers wxphp_wxAuiManager_object_handlers;
void php_wxAuiManager_destruction_handler(zend_resource*);

class wxAuiManager_php: public wxAuiManager{
    public:

    wxAuiManager_php(wxWindow* managed_wnd=NULL, unsigned int flags=wxAUI_MGR_DEFAULT):wxAuiManager(managed_wnd, flags){}
    
    bool ProcessDockResult(wxAuiPaneInfo& target, const wxAuiPaneInfo& new_pos);
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxAuiManager{
    wxAuiManager_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxAuiManager;

void php_wxAuiManager_free(void *object);
zend_object* php_wxAuiManager_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxAuiManager_functions[] = {
    PHP_ME(php_wxAuiManager, __construct, arginfo_void, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxAuiManager, Update, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, UnInit, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, ShowHint, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, SetManagedWindow, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, SetDockSizeConstraint, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, SetFlags, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, SetArtProvider, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, SavePerspective, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, SavePaneInfo, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, LoadPerspective, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, LoadPaneInfo, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, InsertPane, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, HideHint, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, GetPane, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, GetManager, arginfo_void, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, GetManagedWindow, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, GetFlags, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, GetDockSizeConstraint, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, GetArtProvider, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, DetachPane, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManager, AddPane, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxAuiManager * php_wxAuiManager_fetch_object(zend_object *obj) {
    return (zo_wxAuiManager *)(
        (char *)(obj) - XtOffsetOf(zo_wxAuiManager, zo)
    );
}

#define Z_wxAuiManager_P(zv) \
    php_wxAuiManager_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxAuiPaneInfo_entry;
extern zend_object_handlers wxphp_wxAuiPaneInfo_object_handlers;
void php_wxAuiPaneInfo_destruction_handler(zend_resource*);

class wxAuiPaneInfo_php: public wxAuiPaneInfo{
    public:

    wxAuiPaneInfo_php(const wxAuiPaneInfo& c):wxAuiPaneInfo(c){}
    wxAuiPaneInfo_php():wxAuiPaneInfo(){}
    
    
    void InitProperties(){
        properties = new void*[2];

        properties[0] = &name;
        properties[1] = &caption;
        
    }

    void UninitProperties(){
        delete[] properties;
    }

    void** properties;

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxAuiPaneInfo{
    wxAuiPaneInfo_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxAuiPaneInfo;

void php_wxAuiPaneInfo_free(void *object);
zend_object* php_wxAuiPaneInfo_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxAuiPaneInfo_functions[] = {
    PHP_ME(php_wxAuiPaneInfo, __construct, arginfo_void, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxAuiPaneInfo, Window, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, TopDockable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Top, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, ToolbarPane, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Show, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, SetFlag, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, SafeSet, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Row, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, RightDockable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Right, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Resizable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Position, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, PinButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, PaneBorder, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Name, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Movable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, MinimizeButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, MinSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, MaximizeButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, MaxSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, LeftDockable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Left, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Layer, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsTopDockable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsToolbar, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsShown, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsRightDockable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsResizable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsOk, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsMovable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsLeftDockable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsFloating, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsFloatable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsFixed, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsDocked, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsDockable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, IsBottomDockable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Icon, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Hide, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, HasPinButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, HasMinimizeButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, HasMaximizeButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, HasGripperTop, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, HasGripper, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, HasFlag, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, HasCloseButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, HasCaption, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, HasBorder, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, GripperTop, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Gripper, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, FloatingSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, FloatingPosition, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Floatable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Float, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Fixed, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Dockable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, DockFixed, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Dock, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Direction, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, DestroyOnClose, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, DefaultPane, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, CloseButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, CentrePane, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Centre, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, CenterPane, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Center, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, CaptionVisible, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Caption, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, BottomDockable, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, Bottom, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, BestSize, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiPaneInfo, __get, wxphp_aui_get_args, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxAuiPaneInfo * php_wxAuiPaneInfo_fetch_object(zend_object *obj) {
    return (zo_wxAuiPaneInfo *)(
        (char *)(obj) - XtOffsetOf(zo_wxAuiPaneInfo, zo)
    );
}

#define Z_wxAuiPaneInfo_P(zv) \
    php_wxAuiPaneInfo_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxAuiManagerEvent_entry;
extern zend_object_handlers wxphp_wxAuiManagerEvent_object_handlers;
void php_wxAuiManagerEvent_destruction_handler(zend_resource*);

class wxAuiManagerEvent_php: public wxAuiManagerEvent{
    public:

    wxAuiManagerEvent_php(wxEventType type=wxEVT_NULL):wxAuiManagerEvent(type){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxAuiManagerEvent{
    wxAuiManagerEvent_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxAuiManagerEvent;

void php_wxAuiManagerEvent_free(void *object);
zend_object* php_wxAuiManagerEvent_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxAuiManagerEvent_functions[] = {
    PHP_ME(php_wxAuiManagerEvent, __construct, arginfo_void, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxAuiManagerEvent, Veto, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManagerEvent, SetPane, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManagerEvent, SetManager, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManagerEvent, SetDC, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManagerEvent, SetCanVeto, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManagerEvent, SetButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManagerEvent, GetVeto, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManagerEvent, GetPane, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManagerEvent, GetManager, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManagerEvent, GetDC, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManagerEvent, GetButton, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxAuiManagerEvent, CanVeto, arginfo_void, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxAuiManagerEvent * php_wxAuiManagerEvent_fetch_object(zend_object *obj) {
    return (zo_wxAuiManagerEvent *)(
        (char *)(obj) - XtOffsetOf(zo_wxAuiManagerEvent, zo)
    );
}

#define Z_wxAuiManagerEvent_P(zv) \
    php_wxAuiManagerEvent_fetch_object(Z_OBJ_P(zv))
#endif //WXPHP_AUI_H_GUARD
